from enum import Enum


class Event(Enum):
    INIT_SESSION = 0
    CLOSE_SESSION = 63
    BUS_DETECTION = 64
    BUS_ROUTE_NUMBER_RECOGNITION = 65
    BUS_DOOR_DETECTION = 66
    SESSION_OK = 128
    BUS_DETECTION_RESULT = 192
    BUS_ROUTE_NUMBER_RECOGNITION_RESULT = 193
    BUS_DOOR_DETECTION_RESULT = 194

