variables:
  PIP_CACHE_DIR: "$CI_PROJECT_DIR/.cache/pip"

cache:
  paths:
    - .cache/pip
    - venv/

before_script:
    - apt-get -yqq update
    - DEBIAN_FRONTEND=noninteractive apt-get -yqq install python3 python3-pip libgl1-mesa-glx libglib2.0-0
    - pip3 install virtualenv
    - virtualenv venv
    - source venv/bin/activate
    - pip3 install -r requirements.txt

Testing:
  stage: test
  script:
    - python3 -m pytest --junitxml=report.xml
  artifacts:
    when: always
    reports:
      junit: report.xml