cache:
  paths:
    - ~/.cache/pip

before_script:
    - apt-get -yqq update
    - apt-get -yqq install python3 python3-pip libgl1-mesa-glx libglib2.0-0
    - pip3 install -r requirements.txt

Testing:
  stage: test
  script:
    - python3 -m pytest
