from enum import Enum


class Event(Enum):
    INIT_SESSION = 0
    BUS_DETECTION = 1
    BUS_ROUTE_NUMBER_RECOGNITION = 2
    BUS_DOOR_DETECTION = 3
    BUS_DETECTION_RESULT = 4
    BUS_ROUTE_NUMBER_RECOGNITION_RESULT = 5
    BUS_DOOR_DETECTION_RESULT = 6
    CLOSE_SESSION = 255
